### ISSUE TITLE
Issue with script not working

### ISSUE THREAD

**Issue by DarkGhost7** [GoAwayNow/HydrausNao#17]
See below 
![image](https://user-images.githubusercontent.com/38810205/147855358-6f20dce9-c9b1-4fdf-aca6-670cd7ac7270.png)

**Comment by DarkGhost7** [comment]
I have the config.ini configured correctly with the api keys

**Comment by FluffBallFloof** [comment]
The Hydrus API calls changed, I'm taking a look at updating it to work with the new version. I'll either fork or pull request a fixed version if I get it working.

**Comment by FluffBallFloof** [comment]
#18 Added a pull request that should fix the API issues.

**Comment by GoAwayNow** [comment]
Merged your pr, should be fixed now.

**Comment by GoAwayNow** [comment]
I just realized, this update causes a conflict with the requirements of saucenao-api and hydrus-api.

@FluffBallFloof, is saucenao-api still working with the newest versions of requests?

**Comment by FluffBallFloof** [comment]
Yeah, the version conflict can be ignored

**Comment by FluffBallFloof** [comment]
I took a look at the API and it doesn't have anything in it that appears that it would be an issue with the new version, but I might want to check what changed too.

**Comment by DarkGhost7** [comment]
Seems to be working fine for me now.

**Comment by 5af64758** [comment]
has the api changed again? i'm getting this error:

Traceback (most recent call last):
  File "HydrausNao/./hydrus_saucenao_search.py", line 398, in <module>
    handle_results(results)
  File "HydrausNao/./hydrus_saucenao_search.py", line 328, in handle_results
    tag_file("hit")
  File "HydrausNao/./hydrus_saucenao_search.py", line 273, in tag_file
    client.add_tags(hashes=line.splitlines(), service_names_to_tags={meta_tag_service: [final_tag]})
TypeError: Client.add_tags() got an unexpected keyword argument 'service_names_to_tags'
