### ISSUE TITLE
unexpected keyword argument 'service_name_to_tags'

### ISSUE THREAD

**Issue by EricBorges2019** [GoAwayNow/HydrausNao#19]
Got the below error trying to run the script

PS R:\Hydrus Network> python .\hydrus_saucenao_search.py
Processing hash: 00a39d1338be503028b771dcf89c3eb311188d88824043ecc9e9bc1a090a882f
hit! 83.96
Traceback (most recent call last):
  File "R:\Hydrus Network\hydrus_saucenao_search.py", line 398, in <module>
    handle_results(results)
  File "R:\Hydrus Network\hydrus_saucenao_search.py", line 328, in handle_results
    tag_file("hit")
  File "R:\Hydrus Network\hydrus_saucenao_search.py", line 273, in tag_file
    client.add_tags(hashes=line.splitlines(), service_names_to_tags={meta_tag_service: [final_tag]})
TypeError: Client.add_tags() got an unexpected keyword argument 'service_names_to_tags'
PS R:\Hydrus Network>

**Comment by ZacTheHac** [comment]
okay, so I just came here to see if there was an update for the same issue.
It stems from the fact that hydrus recently migrated their tag service to be handled differently to support multiple tag sets and whatever. long story short, you're gonna need to get your hands a little dirty:

in your config.ini, you need to add a new keypair under [Hydrus_Meta_Tags] called service.
Next go into your client, click service>review services>tags>copy service key
set that as the value for service (IE: service = ******************** should be a new line under the [Hydrus_Meta_Tags] category.)
Next, open the hydrus_saucenao_search.py file. on line 273, you should see "client.add_tags(....."
Replace the "service_names_to_tags=" with "service_keys_to_tags="
And there you go.
![should look something like this](https://github.com/GoAwayNow/HydrausNao/assets/7144613/6471ee27-ab86-4f4f-a7f0-e3d6267ade6e)
